### ISSUE TITLE
Vanilla YouTube when starting TizenBrew->TizenTube (with ads, no SponsorBlock)

### ISSUE THREAD

**Issue by muja** [reisxd/TizenTube#64]
Sometimes when starting TizenTube via TizenBrew, none of the add ons are activated unfortunately. This becomes obvious only when starting a video which makes it very annoying e.g. after having searched for a video. Sometimes this happens multiple times in a row. I'm guessing there is an error/timeout when loading the modules somewhere which leads to the entire add-on stack to be discarded?

This happens 2019 Samsung TV, around 30% of the time when launching the app.

**Comment by McBoat-Inc** [comment]
I don't know about TizenBrew, but I've been running TizenTube standalone and previously, when this would happen, it was because I didn't close the app and then opened it without having exited out fully after the last session, which resulted in ads and stuff. However, it could be fixed by simply exiting the app and entering it again. As of a couple of weeks ago, it hasn't been working, and the ads simply fail to skip very often now, even after several restarts of the app for some reason. I think it works sometimes but it's unreliable now

**Comment by Toltally-suck-at-code** [comment]
I think the issue because youtube has been trying server side ad injections recently. I think it somewhat might contribute to this issue. 

I just installed it recently and it worked for a few hours before it started showing ads agian. But the ads are just mid-roll ads. The ads which are in the youtube feed or at the start of the video doesn't show up so it shows that it's working, just youtube f*cking us over....

**Comment by muja** [comment]
> I think the issue because youtube has been trying server side ad injections recently. I think it somewhat might contribute to this issue.
> 
> I just installed it recently and it worked for a few hours before it started showing ads agian. But the ads are just mid-roll ads. The ads which are in the youtube feed or the pre-roll ads doesn't show up so it shows that it's working, just youtube f*cking us over....

Since when has YouTube been "trying" server side ads? I've been getting this bug for at least 2-3 months sporadically

**Comment by muja** [comment]
Hey @reisxd, this still happens from time to time for me (it has become rarer though)
