### ISSUE TITLE
Videos don't play when leaving the app and returning

### ISSUE THREAD

**Issue by muja** [reisxd/TizenTube#65]
Videos don't play when I soft-close/suspend the app and return. This is 100% reproducible for me. My current very annoying workaround is to hard-close the app (by holding the back button for 3 seconds), and then reboot TizenTube. However this makes it that progress is lost and I have to search the video again (if it happened during playback, for instance by accidentally clicking the Netflix button). Additionally, due to #64 this is sometimes very tedious, having to restart the app multiple times to get it into a working state.

**Comment by davidvn001** [comment]
same issue to me

**Comment by szdolhan** [comment]
Same here

**Comment by coldspider7** [comment]
Same with mine.

**Comment by reisxd** [comment]
This is something that I cannot probably fix.

**Comment by evlo** [comment]
I think this is first issue about this.

The issue is that the service does not start on quick resume, or whatever it is called, so in the past it resulted in adds showing, it is still the case, but only ad that show is on the homepage (because videos do not play since some release). 
Well rarely it still occurs that one starts the video and app start playing - i guess because "service" is not started - this is detectable by not seeing message about color buttons in top right corner on youtube app start up. As far as I can tell it never happens after wakeup as aster wakeup video never plays.

This happens both when putting tv into standby and later turning it or, and also most of the time when just switching input for app (or maybe even switching between apps).

It seems to be related to some kind of quick resume.

When you force quick app by HOLDING back button on remote and starting tizenbrew it quits on first lunch, quits and lunches itself back again with message about about starting service - this seems to be root cause.

If it would be possible to detect quick resume, or disable it, maybe it would be enough for app to just restart itself on quick resume or if it is possible to disable it, maybe even tizen/tv can do it itself.

I'm not sure how all this works at all, but seems to be mostly javascript, so maybe it would be possible to add option to run the "server" locally on router/ha/other server that is always on and that way TV can always connect?
Also I noticed tv connects slower to the internet when i'm using ethernet, which i do, so this might also be related, but since the service is running locally, i find it doubfull.
