### ISSUE TITLE
Please read this issue before creating a new one

### ISSUE THREAD

**Issue by reisxd** [reisxd/TizenTube#74]
Most of the current issues are related to YouTube thinking that TizenTube is basically running on a very old TV due to its user agent. Some of these issues include:
* Video segments not showing up
* Long press menu not working
* Video thumbnails being low quality
* Voice search not being available
* and more that's not written here.

All of these issues could be fixed but the problem is, when you change the user agent to be something newer, YouTube changes the CSP (Content Security Policy) to only allow requests to YouTube and nowhere else, which affects SponsorBlock and DeArrow.

Fixing SB and DA is pratically impossible because you can't really bypass CSP. It's a security feature and finding a way to bypass it would be bad news for browsers.

**Comment by IntelCorei5-8350u** [comment]
How about making a separate version with all of the missing features mentioned, without sponsorblock and dearrow? Sponsorblock will still loop endlessly if the segment is too short https://github.com/reisxd/TizenTube/issues/27 and not too many people I have linked this tutorial uses dearrow. Voice search is the feature they wish it back the most.

**Comment by DeadSomeOne** [comment]
> How about making a separate version with all of the missing features mentioned, without sponsorblock and dearrow? Sponsorblock will still loop endlessly if the segment is too short #27 and not too many people I have linked this tutorial uses dearrow. Voice search is the feature they wish it back the most.
@IntelCorei5-8350u You are welcome to use https://github.com/DeadSomeOne/TizenBrew. My fork has 2 user agents added, QN was gotten directly from a TV, RU was halfly guessed, brakes sometimes. In addiction the requirement to recompile yourself, you need to get a partner certificate.

**Comment by IntelCorei5-8350u** [comment]
Thanks for the effort.

Well I don't know how to recompile stuff, and since what I did is to share
(redo) the installation tutorial step-by-step for everyone to understand in
Vietnamese, an official solution with the existing installation methods is
much more appreciated.

Still, thank you for making the fork. Our developer can probably have a
look and adjust things accordingly.

Vào 22:11, Th 2, 22 thg 7, 2024 DeadSomeOne ***@***.***> đã
viết:

**Comment by DeadSomeOne** [comment]
> Thanks for the effort.
>
>Well I don't know how to recompile stuff, and since what I did is to share
(redo) the installation tutorial step-by-step for everyone to understand in
Vietnamese, an official solution with the existing installation methods is
much more appreciated.
>
>Still, thank you for making the fork. Our developer can probably have a
look and adjust things accordingly.

I don't plan on making any releases. I just told a solution to your problem(s). A guide how to compile is given in [tizenbrew repo](https://github.com/reisxd/TizenBrew/blob/main/docs/README.md#rebuilding-tizenbrew), up to you how much effort you are willing to make to solve your community problem. If you have any more inquiries, join the discord server, as I don't want to spam this issue anymore and will not reply here

**Comment by IntelCorei5-8350u** [comment]
Also my last reply. Since this is a mod of tizenbrew, not the tizentube
module so if I wanted to distribute to others, I have to also recompile the
tizenbrew installer, both the web version (which costs money to host a
website) and the executable which I also have to recompile. Not a viable
way for an user, which I am. I can install premade stuff from guides, not
making them from scratch.

I don't use discord, so the only way I can interact with the developer and
other supporters is through github issues & pull requests.

They wanted voice search back, but since I told them it's not supported
most of them moved on anyway, a better trade off than all of those scam
medicine ads found on Vietnamese YouTube, and only on the TV version.

Vào 22:47, Th 4, 24 thg 7, 2024 DeadSomeOne ***@***.***> đã
viết:
